# -*- coding: utf-8 -*-
"""Actividad Semana 5 Parcial 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13bnAM4GvXSNXIwANP07fskPHO1AjAblf
"""

# Importar las librerías
import filecmp
import json
import mysql.connector
import pandas as pd

# Conectar a la base de datos
conn = mysql.connector.connect(
    host="localhost",
    user = "root",
    password="root",
    database="diccionario_db",
)

# Crear un cursor
cursor = conn.cursor()

# Cargar datos del archivo JSON
with open("diccionario_zapoteco.json", 'r' encoding="utf-8") as file:
    diccionario_data = json.load(file)

# Recorrer el diccionario y insertar datos en la base de datos
for palabra in diccionario_data.keys():
    zapoteco = zapoteco
    Español = palabra[Español]

    # Insertar la palabra en la base de datos
    insert_query = "INSERT INTO diccionario_json (zapoteco, Español) VALUES (%s, %s)"
    cursor.execute(insert_query, (zapoteco, Español))

# Confirmar los cambios
conn.commit()

cursor = conn.cursor()
cursor.execute("SELECT zapoteco, Espanol from diccionario_json")
resultados = cursor.fetchall()

# Cerrar el cursor y la conexión
cursor.close()
conn.close()

"""# Sección nueva"""